### ISSUE TITLE
Add CI workflow to run unit tests with latest from Woodwork main 

### ISSUE THREAD

**Issue by gsheni** [alteryx/featuretools#1926]
- We should add a CI workflow that does the following:

1. Install Featuretools 
2. Install Woodwork from the `main` branch
3. Verify that the Featuretools unit tests run

This workflow should run on the following:
```yaml
on:
  schedule:
    - cron: '0 * * * *'
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - main
  workflow_dispatch:
```
